### ISSUE TITLE
loadings() is exported in NAMESPACE but not defined

### ISSUE THREAD

**Issue by johnfrombluff** [mronkko/matrixpls#3]
Hi Mikko, first, thanks so much for this software! I'm following your publications and keen to help with any large-scale simulation programmes you're planning, if you need someone to do some grunt work. I plan to do some simulations of my own, so it would be great to coordinate, if not collaborate :-)

I've just pulled the latest version. It builds, but exhibits the problem in the title of this issue. Also, when I run make check (in RStudio) it failed because a package was missing (ASGSCA: should it be added as a dependency?). And now it's failing one of the tests, probably for the same reason (loadings undefined). 

I have the development versions of lavaan and simsem installed.

Output from R CMD CHECK:

Loading required package: simsem
Loading required package: lavaan
This is lavaan 0.5-20
lavaan is BETA software! Please report any bugs.
 
###############################################################################################
This is simsem 0.5-11
simsem is BETA software! Please report any bugs.
simsem was developed at the University of Kansas Center for Research Methods and Data Analysis.
###############################################################################################
Progress: 1 / 100 
Progress: 2 / 100 
[snip]
Progress: 99 / 100 
Progress: 100 / 100 
RESULT OBJECT
Model Type
[1] "function"
========= Fit Indices Cutoffs ============
                   Alpha
Fit Indices           0.1  0.05  0.01 0.001  Mean    SD
  min cr               NA    NA    NA    NA   NaN    NA
  min ave              NA    NA    NA    NA   NaN    NA
  min ave - sq. cor    NA    NA    NA    NA   NaN    NA
  goodness of fit   0.362 0.374 0.394 0.395 0.329 0.026
========= Parameter Estimates and Standard Errors ============
          Estimate Average Estimate SD
eta1~ksi             0.010       0.087
eta2~eta1            0.440       0.047
eta3~eta1            0.522       0.038
ksi=~Y1              0.729       0.282
ksi=~Y2              0.696       0.323
ksi=~Y3              0.694       0.270
ksi=~Y4              0.691       0.372
eta2=~Y5             0.854       0.017
eta2=~Y6             0.852       0.017
eta2=~Y7             0.856       0.018
eta2=~Y8             0.854       0.017
eta3=~Y9             0.852       0.020
eta3=~Y10            0.850       0.018
eta3=~Y11            0.854       0.018
eta3=~Y12            0.852       0.017
eta1<~X1             0.454       0.079
eta1<~X2             0.465       0.085
eta1<~X3             0.443       0.078
Error in if (sum(variableCol) >= 2) { : 
  missing value where TRUE/FALSE needed
Calls: summary -> summary -> .local
Execution halted
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 5 WARNINGs, 4 NOTEs

**Comment by mronkko** [comment]
I am refactoring some of the code and not all tests and documentation are updated yet. For now you can just build the package without testing. I will try to fix the documentation and tests this week so that you can check without warnings.

If you want to discuss research, you can email me at mikko.ronkko@aalto.fi

**Comment by mronkko** [comment]
Fixed the documentation and namespace issues.

**Comment by johnfrombluff** [comment]
Fantastic, thanks so much! I'll email you in a few days, once I've had time to digest the latest literature.
